### ISSUE TITLE
Snake-case struct members

### ISSUE THREAD

**Issue by alensiljak** [alensiljak/interactive-brokers-flex-rs#2]
https://github.com/alensiljak/interactive-brokers-flex-rs/commit/60eb6b4e6d45c10de1d91cdd24f864e5b0d8c343#r96402214

Use attribute rewriting.

**Comment by pronebird** [comment]
For reference:

https://serde.rs/container-attrs.html

You can rewrite keys for the entire struct with serde's `rename_all` or use `rename` on individual fields:

```rs
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct S {
  first_name: String,

  #[serde(rename = "LAST_NAME")]
  last_name: String
}
```

Also see example: https://serde.rs/attr-rename.html

**Comment by alensiljak** [comment]
Thank you!

**Comment by alensiljak** [comment]
Done in v0.5.

**Comment by alensiljak** [comment]
@pronebird, thank you for the pointers. This was a quick rewrite of my Python scripts and I was focusing on getting the basics ported over. 
Now that it works as expected, it may be further expanded and/or improved.

**Comment by pronebird** [comment]
@alensiljak YW. I am not really using this crate though. I made my own parser a little while ago and I was just passing by when I noticed that you could improve your structs.
